// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS8pHWJfF0V6i5clBjlPid8GnWOZSx4WM',
    appId: '1:247049040938:web:b0e80b226ab7fd130f3f53',
    messagingSenderId: '247049040938',
    projectId: 'event-mager',
    authDomain: 'event-mager.firebaseapp.com',
    storageBucket: 'event-mager.firebasestorage.app',
    measurementId: 'G-YHRR73PM9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQZEKsAx-vLLoZmepz2MVC5ph_axVC87o',
    appId: '1:247049040938:android:fdada1cdcb8b63610f3f53',
    messagingSenderId: '247049040938',
    projectId: 'event-mager',
    storageBucket: 'event-mager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7PJ-0kWiUxZM6s_ckef3V-OlMykfsKRs',
    appId: '1:247049040938:ios:0b8c8d59fa0291af0f3f53',
    messagingSenderId: '247049040938',
    projectId: 'event-mager',
    storageBucket: 'event-mager.firebasestorage.app',
    iosBundleId: 'com.example.eventManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7PJ-0kWiUxZM6s_ckef3V-OlMykfsKRs',
    appId: '1:247049040938:ios:0b8c8d59fa0291af0f3f53',
    messagingSenderId: '247049040938',
    projectId: 'event-mager',
    storageBucket: 'event-mager.firebasestorage.app',
    iosBundleId: 'com.example.eventManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS8pHWJfF0V6i5clBjlPid8GnWOZSx4WM',
    appId: '1:247049040938:web:ce8044593527c04a0f3f53',
    messagingSenderId: '247049040938',
    projectId: 'event-mager',
    authDomain: 'event-mager.firebaseapp.com',
    storageBucket: 'event-mager.firebasestorage.app',
    measurementId: 'G-YNKMRX743P',
  );
}
